Models/Equipe.cs
using System;
using System.Collections.Generic;
using System.IO;
using e_players_completo.Interfaces;

namespace e_players_completo.Models
{
    //HERANÇA DE DUAS CLASSES
    public class Equipe : EPlayersBase, IEquipe
    {
        //PROPRIEDADES/ATRIBUTOS
        public int IdEquipe { get; set; }
        public string Nome { get; set; }
        public string Imagem { get; set; }
        private const string PATH = "Database/equipe.csv";

        //CONSTRUTOR
        public Equipe() {
            CreateFolderAndFile(PATH);
        }

        /// <summary>
        ///     Formata cada linha do csv.
        /// </summary>
        /// <param name="_equipe">Objeto que terá seus dados separados por ";".</param>
        /// <returns>Retorna uma string com os dados separados por ";".</returns>
        private string PrepararLinha(Equipe _equipe) {
            return $"{_equipe.IdEquipe};{_equipe.Nome};{_equipe.Imagem}";
        }

        /// <summary>
        ///     Adiciona no bd.
        /// </summary>
        /// <param name="_equipe">Objeto a ser adicionado no bd.</param>
        public void Create(Equipe _equipe)
        {
            var linhas = new string[] {PrepararLinha(_equipe)};
            File.AppendAllLines(PATH, linhas);
        }

        /// <summary>
        ///     Deleta um cadastro do bd.
        /// </summary>
        /// <param name="_idEquipe">Id do cadastro a ser deletado.</param>
        public void Delete(int _idEquipe)
        {
            List<string> linhas = ReadAllLinesCSV(PATH);
            linhas.RemoveAll(x => x.Split(";")[0] == _idEquipe.ToString());
            RewriteCSV(PATH, linhas);
        }

        /// <summary>
        ///     Lê todos os cadastros do bd.
        /// </summary>
        /// <returns>Retorna uma lista de todos os objetos cadastrados no bd.</returns>
        public List<Equipe> ReadAll()
        {
            List<Equipe> equipes = new List<Equipe>();
            string[] linhas = File.ReadAllLines(PATH);
            foreach (var item in linhas)
            {
                string[] linha = item.Split(";");
                Equipe equipe = new Equipe();
                equipe.IdEquipe = Int32.Parse(linha[0]);
                equipe.Nome = linha[1];
                equipe.Imagem = linha[2];

                equipes.Add(equipe);
            }
            return equipes;
        }

        /// <summary>
        ///     Atualiza um cadastro do bd.
        /// </summary>
        /// <param name="_equipe">Objeto a ser atualizado.</param>
        public void Update(Equipe _equipe)
        {
            List<string> linhas = ReadAllLinesCSV(PATH);
            linhas.RemoveAll(x => x.Split(";")[0] == _equipe.IdEquipe.ToString());
            linhas.Add( PrepararLinha(_equipe) );
            RewriteCSV(PATH, linhas);
        }
    }
}

Controllers/EquipeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using e_players_completo.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace e_players_completo.Controllers
{
    public class EquipeController : Controller
    {
        //Instanciamos o nosso model, assim, teremos acesso ao nosso banco de dados e todos métodos do CRUD.
        Equipe equipeModel = new Equipe();

        /// <summary>
        ///     Este método lê nosso bd e guarda em uma ViewBag. 
        /// </summary>
        /// <returns>Retorna a nossa view.</returns>
        public IActionResult Index()
        {
            ViewBag.Equipes = equipeModel.ReadAll();
            return View();
        }

        /// <summary>
        ///     Cadastra no bd a partir de um form no front.
        /// </summary>
        /// <param name="form">Form do front.</param>
        /// <returns>Retorna para a mesma página após concluir a ação..</returns>
        public IActionResult Cadastrar(IFormCollection form) {

            Equipe equipe   = new Equipe();
            equipe.IdEquipe = Int32.Parse( form["IdEquipe"] ); //Pega o valor do form que tem este name e joga na variável IdEquipe do objeto.
            equipe.Nome     = form["Nome"];

            //Aqui começa upload de imagens
            equipe.Imagem   = form["Imagem"];
            var file    = form.Files[0]; //Esta variável guarda o nome do arquivo da imagem.
            var folder  = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Equipes"); //Esta variável combina o caminho do diretório atual com o "wwwroot/img/Equipes", onde ficará a imagem.

            //Se o usuário enviou alguma imagem..
            if(file != null)
            {
                //Vai verificar se existe a pasta, se não existir, cria.
                if(!Directory.Exists(folder)){
                    Directory.CreateDirectory(folder);
                }

                //Esta variável vai criar e guardar o caminho completo. Note que o Path.Combine ele faz mais do que unir duas variáveis. Por exemplo, se um parâmetro for temp e outro for temp.txt, o path combine será temp.txt.
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/", folder, file.FileName);
                
                //Usando FileStream, passa-se o caminho onde ficará a imagem e cria o arquivo.
                using (var stream = new FileStream(path, FileMode.Create))  
                {  
                    //Copia o arquivo guardado em "file" para o "stream".
                    file.CopyTo(stream);  
                }

                //Guarda-se o caminho da imagem no banco de dados.
                equipe.Imagem   = file.FileName;
            }
            else //<- Se o usuário não mandar um arquivo, salva-se o seguindo no bd:
            {
                equipe.Imagem   = "padrao.png";
            }
            //Fim

            equipeModel.Create(equipe); //Insere o objeto criado no bd.

            ViewBag.Equipes = equipeModel.ReadAll(); //Lê tudo do csv e guarda em uma lista. A ViewBag recebe esta lista. A viewbag é criada aqui.
            return LocalRedirect("~/Equipe"); //Esta página, Equipe, é criada na view, com a sintaxe Razor.
        }

        //Adicionamos a rota do item a ser excluido.
        [Route("Equipe/{id}")]
        /// <summary>
        ///     Exclui um item da view e do bd.
        /// </summary>
        /// <param name="id">Id do item a ser excluído, que é enviado pela rota.</param>
        /// <returns>Retorna para a mesma página.</returns>
        public IActionResult Excluir(int id) {
            equipeModel.Delete(id);
            ViewBag.Equipes = equipeModel.ReadAll();
            return LocalRedirect("~/Equipe");
        }
    }
}

Views/Equipe/Index.cshtml
<!-- Cria um local chamado Equipe, usando a sintaxe Razor, que é o arroba -->

@model Equipe 
@{
    //Nossa ViewData, nossa View, chama-se Equipes.
    ViewData["Title"] = "Equipes";
}

<div class="titulo_pagina">
    <h1>cadastro de @ViewData["Title"]</h1>
</div>

<!-- Este form usa um método do controller, chamado Cadastrar. Nele, pegamos os valores dos inputs e cadastramos no banco de dados. -->
<form class="cadastro" action="@Url.Action("Cadastrar")" method="POST" enctype="multipart/form-data"> <!--Usamos POST pois é melhor e mais seguro. Quando há envio de arquivos, precisa-se usar este enctype.-->

    <div class="campo">
        <label for="IdEquipe">Id</label>
        <input type="text" name="IdEquipe" id="IdEquipe">
    </div>
    
    <div class="campo">
        <label for="Nome">Nome</label>
        <input type="text" name="Nome" id="Nome">
    </div>
    
    <div class="campo">
        <label for="Imagem">Imagem</label>
        <input type="file" name="Imagem" id="Imagem"> <!--type= file-->
    </div>

    <!-- Ao clicar em um botão submit, concluímos a ação. -->
    <button class="gradient btn" type="submit">Cadastrar</button>

</form>

<!-- Percorremos nossa viewbag e adicionamos cada valor em nossa tabela. Nossa viewbag.Equipes é preenchida no método cadastrar e preenchida no bloco de código acima. -->
<table class="table table-striped table-responsive">

    <thead>
        <th>Id</th>
        <th>Nome</th>
        <th>Imagem</th>
    </thead>
    <tbody>
        @foreach(var item in ViewBag.Equipes) {
            <tr>
                <td>@item.IdEquipe</td>
                <td>@item.Nome</td>
                <td><img src="img/Equipes/@item.Imagem" alt="Imagem da equipe @item.Nome" width="40"></td>
                @*Comentário em Razor-> Vai usar o controlador de Equipe, o método Excluir deste controlador, e vai atribuir o valor à rota.*@
                <td><a asp-controller="Equipe" asp-action="Excluir" asp-route-id="@item.IdEquipe"> <i class="fa fa-trash"></i> </a></td>
            </tr>
        }
    </tbody>

</table>